baseURL = "http://dakota-marshall.github.io/"
languageCode = "en-us"
title = "Dakota Marshall"
theme = "hello-friend-ng"
paginate = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "Insert Catchy Tagline Here"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Dakota's Website"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[[params.social]]
  name = "keybase"
  url = "https://keybase.io/dmarshall549"

[languages]
  [languages.en]

    [languages.en.params.logo]
      logoText = "cd ~/"
      logoHomeLink = "/"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "Posts"
    name       = "Posts"
    url        = "/posts"