baseURL = "http://dakotamarshall.net/"
staticDir = 'static'
languageCode = "en-us"
title = "Dakota Marshall"
theme = "hello-friend-ng"
paginate = 10
copyright = <a rel="me" href="https://noc.social/@diobolic"></a>
publishdir = "docs/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "RHCSA || Linux Administrator || Privacy Advocate"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Dakota Marshall || Linux Admin"
  keywords = "homepage, blog, tech"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Enable theme toggle
  # 
  # This options enables the theme toggle for the theme. 
  # Per default, this option is off. 
  # The theme is respecting the prefers-color-scheme of the operating systeme. 
  # With this option on, the page user is able to set the scheme he wants. 
  enableThemeToggle = true

[[params.social]]
  name = "keybase"
  url = "https://keybase.io/dmarshall549"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/dakotamarshall549/"

[[params.social]]
  name = "email"
  url = "mailto:me@dakotamarshall.net"

[[params.social]]
  name = "github"
  url = "https://github.com/dakota-marshall"

[[params.social]]
  name = "gitlab"
  url = "https://gitlab.com/dakota.marshall"

[params.footer]
copyright = false
rss = true

[languages]
  [languages.en]

    [languages.en.params.logo]
      logoText = "cd ~/"
      logoHomeLink = "/"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "Posts"
    name       = "Posts"
    url        = "/posts"

  [[menu.main]]
    identifier = "About Me"
    name       = "About Me"
    url        = "/about-me"

